### ISSUE TITLE
More docs

### ISSUE THREAD

**Issue by wooorm** [lhafkamp/minor-instagram-sockets#5]
Such as a list of todos, a wish-list, etc.

**Comment by lhafkamp** [comment]
Apologies for the lackluster readme, been struggling a lot with the technical aspects of the assignment. Trying to tenaciously understand oauth and mongodb took a lot of my time and doesn't help me with the minimal viable product, hopefully it helps me out in the long run (I think I got it now).

Still appreciate that you reviewed my repo even though there wasn't much to show yet. Expect a good README soon!
